services:
  app:
    container_name: erdmaschine_app
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db/postgres?user=${DB_USER}&password=${DB_PW}"
      AUTH_TOKEN: "${AUTH_TOKEN}"
      REDDIT_CLIENT_ID: "${REDDIT_CLIENT_ID}"
      REDDIT_CLIENT_SECRET: "${REDDIT_CLIENT_SECRET}"

  db:
    container_name: erdmaschine_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "${DB_PW}"
      POSTGRES_USER: "${DB_USER}"
