name: Build

on: [ push ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - run: mvn -B package --file pom.xml

      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: github.ref == 'refs/heads/deploy-flyio'

      - run: flyctl deploy --remote-only
        if: github.ref == 'refs/heads/deploy-flyio'
